# Generated by Django 5.0.6 on 2024-05-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='Dueño',
        ),
    ]
